name: github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        dotnet: ['6.0.x']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: '6.0.x'
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          include-prerelease: true
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build